"""Write `STATUTES-BY-DATE.md`: every statute in the corpus, oldest first.

Re-running produces byte-identical output. Nothing here calls the network.

    uv run python apps/statute-browser/build_statutes_by_date.py
    uv run python apps/statute-browser/build_statutes_by_date.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

APP_DIR = Path(__file__).resolve().parent
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from loader import load_statutes  # noqa: E402

OUTPUT = APP_DIR / "STATUTES-BY-DATE.md"

ERAS = [
    (0, 1948, "Colonial Ceylon (to 1948)", "Passed by the colonial legislature, so almost all are Ordinances."),
    (1948, 1972, "Dominion of Ceylon (1948-1971)", "Parliament of Ceylon. Acts."),
    (1972, 1978, "First Republic (1972-1977)", "National State Assembly. Instruments of this period are Laws."),
    (1978, 9999, "Second Republic (1978 onward)", "Parliament of Sri Lanka. Acts."),
]


def _cite(row) -> str:
    if row.act_no and pd.notna(row.year):
        return f"No. {row.act_no} of {row.year}"
    if not row.in_registry:
        return "index-only"
    return "not recorded"


def _changes(row) -> str:
    if pd.isna(row.first_change):
        return "none recorded"
    if row.first_change == row.last_change:
        return str(row.first_change)
    return f"{row.first_change}-{row.last_change}"


def render() -> str:
    frame = load_statutes().sort_values(
        ["dated_year", "statute"], kind="stable", na_position="last"
    )
    dated = frame[frame["dated_year"].notna()]
    undated = frame[frame["dated_year"].isna()]

    lines = [
        "# Statutes by date",
        "",
        f"All {len(frame)} statutes the corpus holds structure for, oldest first.",
        "Generated by `build_statutes_by_date.py`; do not edit by hand.",
        "",
        "A statute is dated by its year of enactment where the registry holds one.",
        f"{int((frame['date_source'] == 'commenced').sum())} are dated by commencement year instead,",
        f"and {len(undated)} have neither. Those are listed last.",
        "",
        "`Changed` is the span of years in which some section of the statute was",
        "amended. `none recorded` means no amendment history was harvested, which is",
        "not the same as unchanged. Every row is `status=unverified`.",
        "",
    ]

    for start, end, title, note in ERAS:
        era = dated[(dated["dated_year"] >= start) & (dated["dated_year"] < end)]
        if era.empty:
            continue
        lines += [f"## {title}", "", note, "", _table(era)]

    if not undated.empty:
        lines += [
            "## Date not recorded",
            "",
            "Index-only statutes with no year in the registry and no commencement date.",
            "",
            _table(undated),
        ]

    return "\n".join(lines).rstrip() + "\n"


def _table(frame: pd.DataFrame) -> str:
    rows = [
        "| Year | Statute | Citation | Sections | Amended | Changed |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in frame.itertuples():
        year = row.dated_year if pd.notna(row.dated_year) else "?"
        mark = "*" if row.date_source == "commenced" else ""
        rows.append(
            f"| {year}{mark} | {row.statute} | {_cite(row)} | {row.sections} | "
            f"{row.amended_sections} | {_changes(row)} |"
        )
    rows.append("")
    if (frame["date_source"] == "commenced").any():
        rows += ["`*` dated by commencement year, not by a year in the registry.", ""]
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.name} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} is up to date")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(APP_DIR.parents[1])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
