// Records the Draftly demo footage against the local app, one clip per beat.
// Usage: node record.cjs [firstStage]   (state.json keeps the matter between runs)
// Synthetic documents only. The matter reference must be new on every full run.
const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require(
  "C:/Users/ASUS/Desktop/desp-web/frontend/node_modules/@playwright/test",
);
const { Recorder } = require("./lib.cjs");

const APP = "http://localhost:4310";
const API = "http://127.0.0.1:8000";
const DOCS = path.join(__dirname, "docs") + "/"; // regenerated by make_docs.py
const STATE = path.join(__dirname, "state.json");
const REF = process.env.MATTER_REF || "RTA-2026-DEMO-SALE-03";
const CLIENT = process.env.CLIENT_REF || "CLIENT-SYN-03";

const state = fs.existsSync(STATE) ? JSON.parse(fs.readFileSync(STATE, "utf8")) : {};
const save = () => fs.writeFileSync(STATE, JSON.stringify(state, null, 2));
const api = async (p, init = {}) => {
  const r = await fetch(API + p, { ...init, headers: { Authorization: "Bearer demo", "Content-Type": "application/json", ...(init.headers || {}) } });
  return r.json();
};

let page, rec;
const role = (r, name, o = {}) => page.getByRole(r, { name, ...o });
const matterUrl = (s = "") => `${APP}/matters/${state.matterId}${s}`;
async function open(url, ready) {
  await page.goto(url, { waitUntil: "load", timeout: 120000 });
  await (ready || page.locator("main h1").first()).waitFor({ timeout: 120000 });
  await page.waitForTimeout(1500);
}

const stages = {
  // 1. Home dashboard, then into a new matter.
  async home() {
    await open(APP + "/");
    await rec.start("01-home");
    await rec.hold(2500);
    await rec.moveTo(page.getByText("Matter pipeline"), { pause: 1200 });
    await rec.moveTo(page.getByText("Research this month"), { pause: 1200 });
    await rec.moveTo(page.getByText("Recent matters").first(), { pause: 1200 });
    await rec.click(role("link", "Create a matter").first(), { after: 2500 });
    await rec.stop();
  },

  // 2. Intake wizard, steps 1-7, with the four synthetic files.
  async intake() {
    if (!page.url().endsWith("/new")) await open(APP + "/new", role("button", "Continue with RTA"));
    await rec.start("02-intake");
    await rec.hold(2000);
    await rec.click(role("button", "Continue with RTA"), { after: 1500 });
    await rec.type(page.getByLabel("Matter reference"), REF);
    await rec.type(page.getByLabel("Optional client reference"), CLIENT);
    await rec.hold(800);
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 2 of 7").waitFor();
    await rec.hold(1500);
    await rec.click(role("button", "Yes", { exact: true }));
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 3 of 7").waitFor();
    await rec.hold(1800);
    await rec.click(role("button", /^Ownership change/));
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 4 of 7").waitFor();
    await rec.hold(1500);
    await rec.click(role("button", /^Transfer by sale/));
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 5 of 7").waitFor();
    await rec.hold(1500);
    await rec.click(role("button", "Whole registered parcel"), { after: 300 });
    await rec.click(role("button", "Ordinary parcel"), { after: 300 });
    await rec.click(role("checkbox", "Natural persons only"), { after: 300 });
    await rec.click(page.getByRole("group", { name: /active dispute/ }).getByRole("button", { name: "No", exact: true }));
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 6 of 7").waitFor();
    await page.getByText(/requirements across/).waitFor({ timeout: 60000 });
    await rec.hold(1200);
    await rec.moveTo(page.getByText(/requirements across/), { pause: 3500 });
    await rec.click(role("button", "Next", { exact: true }));
    await page.getByText("Step 7 of 7").waitFor();
    await rec.hold(2000);
    await rec.moveTo(page.getByRole("button", { name: /^Choose documents/ }), { pause: 600 });
    await page.locator('input[type="file"]').setInputFiles(
      ["synthetic-identity-card.png", "synthetic-title-certificate.png", "synthetic-form8-instrument.png", "synthetic-survey-plan.png"].map((f) => DOCS + f),
    );
    await rec.hold(2500);
    await rec.click(role("button", "Create a matter", { exact: true }), { after: 300 });
    await page.waitForURL(/\/matters\/mat_/, { timeout: 120000 });
    state.matterId = page.url().match(/matters\/(mat_[^/]+)/)[1];
    save();
    await page.getByText(/files waiting to be processed/).waitFor({ timeout: 60000 });
    await rec.hold(3000);
    await rec.stop();
  },

  // 3. Process the four files and see them classified.
  async process() {
    if (!page.url().includes(state.matterId)) await open(matterUrl("/documents"));
    await rec.start("03-process");
    await rec.hold(1500);
    await rec.click(role("link", "Ready to process"), { after: 300 });
    await page.waitForURL(/processing/);
    await role("button", "Process", { exact: true }).first().waitFor();
    await rec.hold(1500);
    for (let i = 0; i < 4; i++) {
      await rec.click(role("button", "Process", { exact: true }).first(), { after: 300 });
      await page.waitForLoadState("networkidle").catch(() => {});
      await rec.hold(1300);
    }
    await rec.hold(1200);
    await rec.click(page.getByRole("link", { name: "Documents", exact: true }).first(), { after: 300 });
    await page.getByRole("heading", { name: "Detected documents" }).waitFor({ timeout: 60000 });
    await rec.hold(1500);
    await rec.moveTo(page.getByRole("cell", { name: "Title certificate" }).first(), { pause: 1500 });
    await rec.moveTo(page.getByRole("cell", { name: /Nic/ }).first(), { pause: 2000 });
    await rec.stop();
  },

  // 4. Lawyer review: title certificate first, field by field, then approve the rest.
  async review() {
    if (!page.url().endsWith("/documents")) await open(matterUrl("/documents"), page.getByRole("heading", { name: "Detected documents" }));
    const row = page.getByRole("row").filter({ hasText: "Title certificate" });
    await rec.start("04-review");
    await rec.hold(1000);
    await rec.click(row.getByRole("link", { name: "Review" }), { after: 300 });
    await page.waitForURL(/review/);
    await page.getByRole("button", { name: /^Approve (all \d+ fields|1 field)/ }).waitFor();
    await rec.hold(2500);
    const text = await page.locator("main").innerText();
    if (text.includes("520005")) throw new Error("Backend still returns the old stub values; restart it before recording.");
    await rec.moveTo(page.getByRole("img", { name: /Corrected document page/ }), { pause: 2500 });
    await rec.click(role("button", "Confirm type"), { after: 1500 });
    await rec.moveTo(page.getByText("AI-extracted values remain unverified"), { pause: 2200 });
    // Approve two fields individually, so the per-field control is visible.
    for (const label of ["Cadastral map no", "Title certificate no"]) {
      const box = page.getByRole("textbox", { name: new RegExp(`^${label}`, "i") });
      if (!(await box.count())) continue;
      await rec.moveTo(box, { pause: 1200 });
      const approve = box.locator("xpath=following::button[normalize-space()='Approve'][1]");
      await rec.click(approve, { after: 1500 });
    }
    await rec.click(page.getByRole("button", { name: /^Approve all/ }), { after: 300 });
    await page.getByRole("link", { name: /Next document|verified facts/i }).waitFor({ timeout: 120000 });
    await rec.hold(2000);
    await rec.stop();

    // Off camera: every remaining document, from the Documents table.
    for (let n = 0; n < 6; n++) {
      await open(matterUrl("/documents"), page.getByRole("heading", { name: "Detected documents" }));
      const link = page.getByRole("link", { name: "Review" }).first();
      if (!(await link.count())) break;
      await link.click();
      await page.waitForURL(/review/);
      const approveAll = page.getByRole("button", { name: /^Approve (all \d+ fields|\d+ fields?)/ });
      await page.getByText(/Pages confirmed|Pages \d/).first().waitFor();
      await page.waitForTimeout(1500);
      const confirm = role("button", "Confirm type");
      if (await confirm.count()) {
        await confirm.click();
        await page.getByText("Type confirmed").waitFor({ timeout: 30000 });
      }
      if ((await approveAll.count()) && (await approveAll.isEnabled())) {
        await approveAll.click();
        await page.getByText("Awaiting approval").first().waitFor({ state: "detached", timeout: 120000 }).catch(() => {});
      }
      await page.waitForTimeout(2000);
    }
    await open(matterUrl("/documents"), page.getByRole("heading", { name: "Detected documents" }));

    await rec.start("05-facts");
    await rec.hold(800);
    await rec.click(page.getByRole("link", { name: "Verified facts", exact: true }).first(), { after: 300 });
    await page.getByRole("heading", { name: /facts verified/ }).waitFor();
    await rec.hold(1500);
    await rec.moveTo(page.getByRole("heading", { name: /facts verified/ }), { pause: 3500 });
    await rec.stop();
  },

  // 5. Deterministic checks; one warning triaged on camera.
  async checks() {
    await open(matterUrl("/checks"), role("button", "Run checks"));
    await rec.start("06-checks");
    await rec.hold(1500);
    await rec.click(role("button", "Run checks"), { after: 300 });
    await role("button", "Run checks").waitFor({ timeout: 120000 });
    await page.getByRole("button", { name: "Record issue decision" }).first().waitFor({ timeout: 60000 });
    await rec.hold(1500);
    await rec.scroll(500, { steps: 25 });
    await rec.hold(1500);
    await rec.scroll(-500, { steps: 25 });
    const first = page.getByRole("button", { name: "Record issue decision" }).first();
    await rec.click(first, { after: 1200 });
    const dlg = page.getByRole("dialog");
    await rec.moveTo(dlg.getByLabel("Target state"), { pause: 400 });
    await dlg.getByLabel("Target state").selectOption({ label: "Triaged" });
    await rec.hold(1500);
    await rec.click(dlg.getByRole("button", { name: "Record resolution" }), { after: 300 });
    await dlg.waitFor({ state: "detached" });
    await rec.hold(2500);
    await rec.stop();

    // Off camera: triage the remaining warnings the same way.
    for (let n = 0; n < 30; n++) {
      const btns = page.getByRole("button", { name: "Record issue decision" });
      let done = false;
      for (let i = 0; i < (await btns.count()); i++) {
        const b = btns.nth(i);
        const card = b.locator("xpath=ancestor::*[.//h3][1]");
        if (await card.getByText("Open", { exact: true }).count()) {
          await b.click();
          await page.getByRole("dialog").getByLabel("Target state").selectOption({ label: "Triaged" });
          await page.getByRole("dialog").getByRole("button", { name: "Record resolution" }).click();
          await page.getByRole("dialog").waitFor({ state: "detached" });
          await page.waitForTimeout(700);
          done = true;
          break;
        }
      }
      if (!done) break;
    }
    await open(matterUrl("/checks"), role("button", "Run checks"));
    await rec.start("07-checks-passing");
    await rec.hold(1200);
    await rec.moveTo(page.getByText(/Registration-ready export/), { pause: 3000 });
    await rec.stop();
  },

  // 6. Grounded statute research, then an unsupported question.
  async research() {
    await open(APP + "/research", page.getByRole("textbox", { name: "Ask a legal research question" }));
    await rec.start("08-research");
    await rec.hold(1200);
    await rec.click(role("button", "New conversation"), { after: 1200 });
    await rec.click(role("button", "Statutes & amendments"), { after: 1200 });
    await rec.type(page.getByRole("textbox", { name: "Ask a legal research question" }),
      "What does the Registration of Title Act say about transferring a registered parcel?", { delay: 35 });
    await rec.click(role("button", "Send"), { after: 300 });
    await page.getByRole("heading", { name: "Sources used" }).last().waitFor({ timeout: 150000 });
    await rec.hold(2000);
    await rec.scroll(700, { steps: 35 });
    await rec.hold(3500);
    await rec.stop();

    await rec.start("09-research-abstain");
    await rec.hold(800);
    await rec.click(role("button", "New conversation"), { after: 1000 });
    await rec.click(role("button", "Statutes & amendments"), { after: 600 });
    await rec.type(page.getByRole("textbox", { name: "Ask a legal research question" }),
      "What is the speed limit for cars on Sri Lankan expressways?", { delay: 35 });
    await rec.click(role("button", "Send"), { after: 300 });
    await page.getByText("No supporting authority").waitFor({ timeout: 150000 });
    await rec.hold(1000);
    await rec.moveTo(page.getByText("Draftly will not fill the gap with uncited text."), { pause: 4000 });
    await rec.stop();
  },

  // 7. Form 8 from verified facts; a few confirmations on camera.
  async draft() {
    await open(matterUrl("/drafts"), role("button", "New draft"));
    await rec.start("10-draft");
    await rec.hold(1200);
    await rec.click(role("button", "New draft"), { after: 300 });
    await page.waitForURL(/drafts\/frm_/, { timeout: 120000 });
    state.formId = page.url().match(/drafts\/(frm_[^/?#]+)/)[1];
    save();
    await page.getByRole("complementary").getByRole("article").waitFor();
    await rec.hold(2500);
    await rec.moveTo(page.getByText("Known source text defects"), { pause: 2500 });
    await rec.moveTo(page.getByText(/blanks filled/), { pause: 1500 });
    await rec.moveTo(page.getByRole("document", { name: "Gazette form" }), { pause: 500 });
    await rec.scroll(900, { steps: 40, pause: 40 });
    await rec.hold(2500);
    await rec.scroll(-900, { steps: 30 });
    await rec.hold(800);
    const side = page.getByRole("complementary");
    await rec.click(side.getByRole("button", { name: "Confirm", exact: true }), { after: 2500 });
    await rec.stop();

    // Two more confirmations, each on a fresh load (the editor drops fast repeats).
    for (const field of [/\(g\) Cadastral Map No\./, /\(b\) Title Certificate No\./]) {
      await open(page.url(), page.getByRole("complementary").getByRole("article"));
      await rec.start(field.source.includes("Cadastral") ? "11-draft-confirm-a" : "12-draft-confirm-b");
      await rec.hold(600);
      await rec.click(page.getByRole("button", { name: field }), { after: 900 });
      await rec.click(page.getByRole("complementary").getByRole("button", { name: "Confirm", exact: true }), { after: 2200 });
      await rec.stop();
    }

    // Off camera: confirm every remaining field, one per load.
    for (let i = 0; i < 40; i++) {
      const form = await api(`/api/v1/forms/${state.formId}`);
      const waiting = form.fields.filter((f) => f.awaitingConfirmation);
      if (!waiting.length) break;
      await open(page.url(), page.getByRole("complementary").getByRole("article"));
      const target = page.getByRole("button", { name: /\(Awaiting confirmation\)$/ }).first();
      const sideBar = page.getByRole("complementary");
      if (await target.count()) {
        await target.click();
      } else {
        // Blanks not printed on the form: walk the sidebar to them.
        for (let j = 0; j < 50; j++) {
          const art = sideBar.getByRole("article");
          if ((await art.count()) && (await art.getByText("Awaiting confirmation").count())) break;
          const next = sideBar.getByRole("button", { name: "Next", exact: true });
          if (await next.isDisabled()) break;
          await next.click();
          await page.waitForTimeout(150);
        }
      }
      await page.waitForTimeout(400);
      await sideBar.getByRole("button", { name: "Confirm", exact: true }).click();
      await page.waitForLoadState("networkidle").catch(() => {});
      await page.waitForTimeout(1200);
    }
  },

  // 8. Preflight, then the lawyer's approval with the declaration.
  async approval() {
    await open(`${matterUrl("/drafts/")}${state.formId}`, page.getByRole("complementary").getByRole("article"));
    await rec.start("13-preflight");
    await rec.hold(800);
    const pre = role("button", "Run preflight");
    await rec.moveTo(pre, { pause: 600 });
    await pre.click();
    await page.waitForTimeout(4000);
    await rec.moveTo(page.getByRole("heading", { name: "Form readiness" }), { pause: 3500 });
    await rec.click(role("link", "Approve", { exact: true }), { after: 300 });
    await page.waitForURL(/approval/);
    await role("button", "Approve", { exact: true }).waitFor({ timeout: 120000 });
    await rec.hold(2500);
    await rec.click(role("button", "Approve", { exact: true }), { after: 1500 });
    await rec.moveTo(page.getByText(/I have reviewed the evidence-linked draft/).first(), { pause: 3500 });
    await rec.click(role("button", "Approve", { exact: true }), { after: 1500 });
    await rec.stop();
    // Off camera: approval can take a while locally.
    for (let i = 0; i < 90; i++) {
      const f = await api(`/api/v1/forms/${state.formId}`);
      if (f.state === "APPROVED") break;
      await page.waitForTimeout(2000);
    }
    await open(page.url());
    await rec.start("14-approved");
    await rec.hold(4000);
    await rec.stop();
  },

  // 9. Approved export, registration events, and the finished stepper.
  async exportReg() {
    await open(matterUrl("/exports"), role("button", "Create export").first());
    await rec.start("15-export");
    await rec.hold(1500);
    await rec.moveTo(page.getByText(/never downloadable files/), { pause: 2500 });
    await rec.click(role("button", "Create export").first(), { after: 1500 });
    await rec.moveTo(page.getByRole("radio", { name: /^Approved manifest/ }), { pause: 1500 });
    await rec.click(role("button", "Create export").nth(1), { after: 3000 });
    const events = [
      ["Attested", "synthetic-form8-instrument.png", ""],
      ["Presented", "synthetic-form8-instrument.png", "Colombo Land Registry (synthetic)"],
      ["Registered", "synthetic-title-certificate.png", "Colombo Land Registry (synthetic)"],
    ];
    const today = new Date().toISOString().slice(0, 10);
    for (const [i, [type, ev, office]] of events.entries()) {
      if (!(await page.locator("main input[type=date]").count())) {
        await rec.click(role("button", "Record registration event"), { after: 900 });
      }
      await rec.moveTo(page.locator("main select").first(), { pause: 300 });
      await page.locator("main select").first().selectOption({ label: type });
      await page.locator("main input[type=date]").fill(today);
      await rec.moveTo(page.locator("#event-evidence"), { pause: 300 });
      await page.locator("#event-evidence").selectOption({ label: ev });
      if (office) await rec.type(page.getByText("Registry office", { exact: true }).locator("xpath=following::input[1]"), office, { delay: i === 1 ? 35 : 10 });
      await rec.hold(800);
      await rec.click(role("button", "Record event"), { after: 2500 });
    }
    await rec.hold(1500);
    await rec.stop();

  },

  // 10. The finished stepper on the matter overview.
  async stepper() {
    await open(matterUrl(""));
    // The stepper sits centred in the matter header (1920-wide layout).
    await rec.start("16-stepper");
    await rec.hold(1500);
    await page.mouse.move(762, 112, { steps: 25 });
    await rec.hold(600);
    await page.mouse.move(1402, 112, { steps: 60 });
    rec.mouse = { x: 1402, y: 112 };
    await rec.hold(2500);
    await rec.stop();
  },
};

const order = ["home", "intake", "process", "review", "checks", "research", "draft", "approval", "exportReg", "stepper"];

(async () => {
  const from = process.argv[2] || "home";
  const only = process.argv[3] === "only";
  const browser = await chromium.launch({ channel: "chromium" });
  page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  page.setDefaultTimeout(30000);
  rec = new Recorder(page);
  await rec.init();
  for (const name of order.slice(order.indexOf(from))) {
    console.log(`== stage ${name}`);
    await stages[name]();
    if (only) break;
  }
  await browser.close();
  console.log("done", state);
})().catch(async (e) => {
  console.error("FAILED:", e.message);
  try { await rec.stop(); } catch {}
  try { await page.screenshot({ path: path.join(__dirname, "failure.png") }); } catch {}
  process.exit(1);
});
