"""Anchor normalization, verbatim-substring search, and slicing.

Mirrors scripts/case-law-information-extraction/validate.py's philosophy
(whitespace-collapsed, lowercased substring match is what makes a model's
output trustworthy) but goes one step further: instead of only checking an
LLM-produced quote against the source after the fact, this locates the exact
original-text character offset of each anchor so the *section text itself*
can be sliced straight from the source, never generated by the model.
"""

from __future__ import annotations

import bisect
import re
from dataclasses import dataclass
from difflib import SequenceMatcher

_WORD_RE = re.compile(r"\S+")
# Mirrors scripts/case-law-information-extraction/validate.py's quote_match():
# a section-opening anchor commonly survives with one small residual margin
# fragment still embedded despite the source-cleaning pass (or the model
# "fixing" an apparent typo it shouldn't have touched), so an anchor that
# fails an exact match gets one more chance via fuzzy alignment before being
# rejected outright -- same 90% character-coverage bar, same digit-guard
# (a section number, date, or amount must still be present) so a near-miss
# can recover a genuine anchor without ever silently swapping a figure.
FUZZY_COVERAGE = 0.90
FUZZY_WINDOW_PAD = 2.0


def _digits(s: str) -> set[str]:
    return set(re.findall(r"\d+", s))


@dataclass
class CollapsedText:
    """A whitespace-collapsed, lowercased view of `original`, plus a map from
    each character in `collapsed` back to its offset in `original`."""

    original: str
    collapsed: str
    index_map: list[int]

    def to_original_offset(self, collapsed_pos: int) -> int:
        if collapsed_pos >= len(self.index_map):
            return len(self.original)
        return self.index_map[collapsed_pos]


def build_collapsed(text: str) -> CollapsedText:
    out_chars: list[str] = []
    index_map: list[int] = []
    prev_space = True  # swallow leading whitespace
    for i, c in enumerate(text):
        if c.isspace():
            if not prev_space:
                out_chars.append(" ")
                index_map.append(i)
                prev_space = True
        else:
            out_chars.append(c.lower())
            index_map.append(i)
            prev_space = False
    return CollapsedText(original=text, collapsed="".join(out_chars), index_map=index_map)


def normalize_anchor(anchor: str) -> str:
    return re.sub(r"\s+", " ", (anchor or "").strip()).lower()


def anchor_word_count(anchor: str) -> int:
    return len(_WORD_RE.findall(anchor or ""))


def find_anchor(
    collapsed: CollapsedText, anchor: str, *, search_from: int = 0
) -> int | None:
    """Return the original-text offset where `anchor` starts, searching no
    earlier than `search_from` (an original-text offset), or None if it
    isn't a genuine substring -- the anchor is rejected, never guessed at."""
    needle = normalize_anchor(anchor)
    if not needle:
        return None
    # search_from is an original offset; find the first collapsed position
    # at or after it (index_map is non-decreasing, so this is a binary search).
    collapsed_start = bisect.bisect_left(collapsed.index_map, search_from)
    if collapsed_start >= len(collapsed.index_map):
        return None
    pos = collapsed.collapsed.find(needle, collapsed_start)
    if pos < 0:
        return None
    return collapsed.to_original_offset(pos)


def fuzzy_find_anchor(
    collapsed: CollapsedText, anchor: str, *, search_from: int = 0, min_len: int = 20
) -> int | None:
    """Second-chance match for an anchor that isn't an exact substring --
    e.g. the model silently dropped one leftover margin word it "helpfully"
    treated as an error. Anchors on the best-aligning region via
    difflib, then requires the anchor's characters to be at least
    FUZZY_COVERAGE covered by matching blocks against a padded window around
    that region, with a hard digit-preservation guard so a near-miss can
    never silently swap a section number, date, or amount.
    """
    needle = normalize_anchor(anchor)
    if len(needle) < min_len:
        return None
    collapsed_start = bisect.bisect_left(collapsed.index_map, search_from)
    if collapsed_start >= len(collapsed.index_map):
        return None
    haystack = collapsed.collapsed[collapsed_start:]

    match = SequenceMatcher(None, needle, haystack, autojunk=False).find_longest_match(
        0, len(needle), 0, len(haystack)
    )
    if match.size == 0:
        return None
    pad = int(len(needle) * FUZZY_WINDOW_PAD)
    win_start = max(0, match.b - pad)
    win_end = min(len(haystack), match.b + match.size + pad)
    window = haystack[win_start:win_end]

    needle_digits = _digits(needle)
    if needle_digits and not needle_digits.issubset(_digits(window)):
        return None

    sm = SequenceMatcher(None, needle, window, autojunk=False)
    covered = sum(block.size for block in sm.get_matching_blocks())
    if covered < max(min_len, FUZZY_COVERAGE * len(needle)):
        return None

    # The anchor is assumed to start at the section boundary, so its first
    # matching block anchors the estimated start -- not the window start.
    first_block = next((b for b in sm.get_matching_blocks() if b.size > 0), None)
    if first_block is None:
        return None
    estimated_collapsed_pos = collapsed_start + win_start + first_block.b - first_block.a
    estimated_collapsed_pos = max(estimated_collapsed_pos, collapsed_start)
    return collapsed.to_original_offset(estimated_collapsed_pos)
