"""Write the LaTeX number macros and appendix tables for the paper from the
dataset and experiment files, so that no number in the paper is typed by
hand.

    uv run python scripts/statutory-qa/make_paper_numbers.py --run main-test --tune-run tune-dev
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import sq_common as C  # noqa: E402

PAPER = C.ROOT / "research-paper"


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--reference", default="S5_hybrid_rerank")
    ap.add_argument("--proposed", default="S7_bundle")
    args = ap.parse_args(argv)

    man = C.read_json(C.CORPUS_DIR / "manifest.json")
    funnel = C.read_json(C.AUDITS_DIR / "gold-funnel.json")
    cf = funnel["candidate_funnel"]
    cov = C.read_json(C.AUDITS_DIR / "authority-coverage.json")
    summ = C.read_json(C.EXPERIMENTS_DIR / "metrics" / args.run / "summary.json")
    cfg = C.read_json(C.EXPERIMENTS_DIR / "configs" / f"{args.run}.json")
    dev = C.read_json(C.BENCHMARK_DIR / "development-ids.json")
    test = C.read_json(C.BENCHMARK_DIR / "test-ids.json")
    gold = C.read_jsonl(C.BENCHMARK_DIR / "private-gold.jsonl")

    ann = funnel["annotation"]
    reserved = sum(funnel["reserved"].values())
    blocked = sum(1 for e in funnel["excluded"] if str(e.get("reason", "")).startswith("blocked"))
    hop = cov["hop_count_distribution"]
    ind = cov["indispensable_sections_per_question"]
    hop3 = sum(v for k, v in hop.items() if int(k) >= 3)
    ind3 = sum(v for k, v in ind.items() if int(k) >= 3)
    ref, ours = summ["systems"][args.reference], summ["systems"][args.proposed]
    paired = ours["paired_vs"][args.reference]["complete@20"]
    s7cfg = next(s["config"] for s in cfg["systems"] if s["system"] == args.proposed)

    lines = [
        "% generated by scripts/statutory-qa/make_paper_numbers.py; do not edit",
        macro("nPrincipal", man["documents"]["principal_enactments"]),
        macro("nAmending", man["documents"]["amending_acts"]),
        macro("nSections", f"{man['sections']:,}"),
        macro("nSectionsPrincipal", f"{man['sections_in_principal_enactments']:,}"),
        macro("nProvisions", f"{man['provisions']:,}"),
        macro("nEdges", f"{sum(man['edges'].values()):,}"),
        macro("nEdgesDefines", f"{man['edges'].get('defines', 0):,}"),
        macro("nEdgesProc", f"{man['edges'].get('procedurally_requires', 0):,}"),
        macro("nEdgesXref", f"{man['edges'].get('cross_references', 0):,}"),
        macro("nEdgesAmends", f"{man['edges'].get('amends', 0):,}"),
        macro("nEdgesQual", f"{man['edges'].get('qualifies', 0):,}"),
        macro("nEdgesExc", f"{man['edges'].get('excepts', 0):,}"),
        macro("nSectionsAmended", f"{man['sections_with_amendment_events']:,}"),
        macro("corpusFingerprint", man["corpus_fingerprint"][:12]),
        macro("nSourceQ", cf["source_questions"]),
        macro("nCandidates", cf["keep_enrich_candidates"]),
        macro("nQuarantined", cf["quarantined_background_boundary_questions"]),
        macro("nTierB", cf["tier_b_questions"]),
        macro("nTierA", cf["tier_a_questions"]),
        macro("nTierAMatters", cf["tier_a_matters"]),
        macro("nAnnotated", ann.get("questions_annotated", 0)),
        macro("nAnnotatedMatters", ann.get("matters_annotated", 0)),
        macro("nStatuteOnly", ann.get("statute_only_proposed_gold", 0)),
        macro("nReserved", reserved),
        macro("nBlocked", blocked),
        macro("nGoldQ", funnel["eligible_gold_questions"]),
        macro("nGoldM", funnel["eligible_gold_matters"]),
        macro("nGoldEnrich", cov["keep_vs_enrich"].get("enrich", 0)),
        macro("nGoldActs", cov["n_statutes_represented"]),
        macro("nGoldIndSecs", cov["indispensable_sections_distinct"]),
        macro("hopOne", hop.get("1", 0)), macro("hopTwo", hop.get("2", 0)), macro("hopThreePlus", hop3),
        macro("indOne", ind.get("1", 0)), macro("indTwo", ind.get("2", 0)), macro("indThreePlus", ind3),
        macro("nMultiAct", sum(v for k, v in cov["acts_per_question"].items() if int(k) > 1)),
        macro("nDevM", len(dev["matters"])), macro("nDevQ", len(dev["questions"])),
        macro("nTestM", len(test["matters"])), macro("nTestQ", len(test["questions"])),
        macro("nBoot", f"{summ['bootstrap']:,}"),
        macro("cAtTwentyRef", f"{ref['metrics']['complete@20']['matter_macro']:.3f}"),
        macro("cAtTwentyOurs", f"{ours['metrics']['complete@20']['matter_macro']:.3f}"),
        macro("cAtTenRef", f"{ref['metrics']['complete@10']['matter_macro']:.3f}"),
        macro("cAtTenOurs", f"{ours['metrics']['complete@10']['matter_macro']:.3f}"),
        macro("rAtTwentyRef", f"{ref['metrics']['recall@20']['matter_macro']:.3f}"),
        macro("rAtTwentyOurs", f"{ours['metrics']['recall@20']['matter_macro']:.3f}"),
        macro("deltaCTwenty", f"{paired['delta']:+.3f}"),
        macro("deltaCTwentyLo", f"{paired['ci_low']:+.3f}"),
        macro("deltaCTwentyHi", f"{paired['ci_high']:+.3f}"),
        macro("actsRetained", s7cfg["acts_retained"]),
        macro("nSeeds", s7cfg["seeds"]),
        macro("graphWeight", s7cfg["graph_support_weight"]),
        macro("runName", args.run),
    ]
    C.write_text(PAPER / "paper-numbers.tex", "\n".join(lines) + "\n")

    tdir = PAPER / "tables"
    tdir.mkdir(exist_ok=True)
    shutil.copy(C.EXPERIMENTS_DIR / "tables" / args.run / "main.tex", tdir / "main.tex")
    abl = C.EXPERIMENTS_DIR / "tables" / args.run / "ablations.tex"
    if abl.exists():
        shutil.copy(abl, tdir / "ablations.tex")
    fdir = PAPER / "figures"
    fdir.mkdir(exist_ok=True)
    for name in ("complete_at_k.pdf", "ablations.pdf"):
        src = C.EXPERIMENTS_DIR / "figures" / args.run / name
        if src.exists():
            shutil.copy(src, fdir / name)

    # config appendix
    fw = s7cfg["field_weights"]
    conf = [
        "\\small",
        f"All runs: corpus fingerprint \\texttt{{{man['corpus_fingerprint'][:12]}}}, run \\texttt{{{args.run}}}, git commit \\texttt{{{(cfg.get('git_commit') or '')[:10]}}}, CPU only.",
        "\\begin{itemize}\\setlength{\\itemsep}{0pt}",
        f"\\item BM25: $k_1=1.2$, $b=0.75$, tokenizer \\texttt{{[0-9a-z]+}} after case folding, closed-class stopword list. Field weights (S2, S4--S7): act title {fw['act_title']}, part heading {fw['part_heading']}, section heading {fw['heading']}, body {fw['body']}, defined terms {fw['defined_terms']}, cross-reference text {fw['xref_text']}.",
        f"\\item Dense: \\texttt{{{cfg['embedding_model']}}}, cosine similarity, query prefix ``{cfg['embedding_query_prefix'].strip()}'', windows of {cfg['chunking']['chars']} characters with stride {cfg['chunking']['stride']}, at most {cfg['chunking']['max_chunks']} windows per section, section score = max over windows.",
        f"\\item Fusion: reciprocal rank fusion with $k={s7cfg['rrf_k']}$, equal channel weights, candidate depth {s7cfg['candidate_depth']}.",
        f"\\item Reranker: \\texttt{{{cfg['reranker_model']}}}, max length 512, passage = act title, heading and the first 2000 characters of the section.",
        f"\\item Routing (S6, S7): Acts scored by the sum of the top {s7cfg['act_score_from_sections']} fused section scores; {s7cfg['acts_retained']} Acts retained; amending Acts folded into their principal enactment.",
        f"\\item Bundle (S7): {s7cfg['seeds']} seeds; expansion over {', '.join(r.replace('_', chr(92) + '_') for r in s7cfg['expansion_relations'])}; temporal filter on; graph-support weight $\\gamma={s7cfg['graph_support_weight']}$; seed bonus 0.05.",
        f"\\item Query: normalised background (enriched where enrichment applied) followed by the question. Split seed {dev['seed']}, development fraction {dev['dev_fraction']}. Bootstrap: {summ['bootstrap']:,} matter-level resamples, seed {summ['seed']}.",
        "\\end{itemize}",
    ]
    C.write_text(tdir / "config.tex", "\n".join(conf) + "\n")

    # CI appendix table: main systems only, four columns, so it fits the text width
    order = [n for n in ("S1_bm25", "S2_bm25f", "S3_dense", "S4_hybrid_rrf", "S5_hybrid_rerank", "S6_hier", "S7_bundle") if n in summ["systems"]]
    cols = ["recall@20", "complete@10", "complete@20", "mrr"]
    pretty = {"S1_bm25": "BM25", "S2_bm25f": "BM25F", "S3_dense": "Dense", "S4_hybrid_rrf": "Hybrid RRF",
              "S5_hybrid_rerank": "Hybrid + CE", "S6_hier": "Hierarchical", "S7_bundle": "Hier. + bundle"}
    rows = ["\\small", "\\begin{tabular}{l" + "c" * len(cols) + "}", "\\toprule", "System & R@20 & C@10 & C@20 & MRR \\\\", "\\midrule"]
    for n in order:
        s_ = summ["systems"][n]
        cells = [f"{s_['metrics'][c]['matter_macro']:.2f} [{s_['metrics'][c]['ci95'][0]:.2f}, {s_['metrics'][c]['ci95'][1]:.2f}]" for c in cols]
        rows.append(f"{pretty[n]} & " + " & ".join(cells) + " \\\\")
    rows += ["\\bottomrule", "\\end{tabular}"]
    pv = ["", "\\medskip", "", "Paired matter-level bootstrap differences, S7 minus the named system (95\\% CI), for complete recall at 20 and indispensable recall at 20:"]
    pv.append("\\begin{itemize}\\setlength{\\itemsep}{0pt}")
    for n in order:
        if n == args.proposed:
            continue
        p_ = summ["systems"][args.proposed]["paired_vs"].get(n)
        sign = 1
        if not p_:
            p_ = summ["systems"][n]["paired_vs"].get(args.proposed)
            sign = -1
        if not p_:
            continue
        c20, r20 = p_["complete@20"], p_["recall@20"]
        lo_c, hi_c = sorted((sign * c20["ci_low"], sign * c20["ci_high"]))
        lo_r, hi_r = sorted((sign * r20["ci_low"], sign * r20["ci_high"]))
        pv.append(f"\\item vs {pretty[n]}: $\\Delta$C@20 {sign * c20['delta']:+.3f} [{lo_c:+.3f}, {hi_c:+.3f}], $\\Delta$R@20 {sign * r20['delta']:+.3f} [{lo_r:+.3f}, {hi_r:+.3f}]")
    pv.append("\\end{itemize}")
    C.write_text(tdir / "main-ci.tex", "\n".join(rows + pv) + "\n")
    print("wrote paper-numbers.tex and tables/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
