"""Write research-paper/tables/statutes.tex: every Act in the frozen corpus,
read from corpus/acts.jsonl so the appendix list is never typed by hand.

    uv run python scripts/statutory-qa/make_statute_table.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import sq_common as C  # noqa: E402

OUT = C.ROOT / "research-paper" / "tables" / "statutes.tex"

EDITION = {
    "consolidated": "consolidated",
    "consolidated-2024": "consolidated",
    "as_enacted": "as enacted",
    "original_or_unconfirmed_consolidation": "unconfirmed",
}


def tex(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%")


def curriculum_categories() -> dict[str, str]:
    """Curriculum category (1, 2, 3) per Act from the summary table of
    data/legal-sources/RUBRIK.md, keyed by 'number-year' and by lower-cased title."""
    import re

    out: dict[str, str] = {}
    path = C.ROOT / "data" / "legal-sources" / "RUBRIK.md"
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"\|\s*([123])\s*\|\s*(.+?)\s*\|\s*No\. (\d+) of (\d{4})\s*\|", line)
        if m:
            cat, title, num, year = m.groups()
            out[f"{num}-{year}"] = cat
            out[title.strip().lower()] = cat
    # the rubric cites the Jaffna ordinance by its 1947 consolidation number and
    # a different word order; the corpus uses the original 1911 enactment
    if "matrimonial rights and inheritance (jaffna) ordinance" in out:
        out.setdefault("jaffna matrimonial rights and inheritance ordinance",
                       out["matrimonial rights and inheritance (jaffna) ordinance"])
    return out


def main() -> int:
    acts = C.read_jsonl(C.CORPUS_DIR / "acts.jsonl")
    cats = curriculum_categories()
    key = lambda a: (a["year"], a["number"])  # noqa: E731
    principal = sorted((a for a in acts if a["kind"] == "principal"), key=key)
    amending = sorted((a for a in acts if a["kind"] == "amendment"), key=key)
    by_id = {a["act_id"]: a for a in acts}

    lines = [
        "% generated by scripts/statutory-qa/make_statute_table.py; do not edit",
        r"\footnotesize",
        r"\begin{longtable}{p{0.50\linewidth}crrrl}",
        r"\caption{Principal enactments in the frozen corpus (" + str(len(principal))
        + r"), by year. Cat.\ is the curriculum category assigned by the Sri Lanka "
        r"Law College conveyancing course tables (1 most important, 3 important). "
        r"Sections are the retrieval units the parser produced. Amend.\ is the number "
        r"of amending Acts held in the corpus as separate documents whose "
        r"\textsc{amends} edges point to the enactment (" + str(len(amending))
        + r" in total, of which " + str(sum(1 for m in amending if not m.get("amends_act_id")))
        + r" record no target and are not counted). Fold.\ is the number of amending "
        r"instruments already folded into the consolidated text. Edition is the text "
        r"the section tree was built from.}\label{tab:principal}\\",
        r"\toprule Enactment & Cat. & Sections & Amend. & Fold. & Edition \\ \midrule \endfirsthead",
        r"\toprule Enactment & Cat. & Sections & Amend. & Fold. & Edition \\ \midrule \endhead",
        r"\bottomrule \endfoot",
    ]
    for a in principal:
        ed = EDITION.get(a["edition_kind"], a["edition_kind"])
        cat = cats.get(f"{a['number']}-{a['year']}") or cats.get(a["title"].strip().lower()) or "--"
        folded = len(a.get("amendments_folded_in") or [])
        n_am = sum(1 for m in amending if m.get("amends_act_id") == a["act_id"])
        lines.append(f"{tex(a['label'])} & {cat} & {a['n_sections']} & {n_am} & {folded} & {ed} \\\\")
    lines.append(r"\end{longtable}")

    C.write_text(OUT, "\n".join(lines) + "\n")
    unlinked = sum(1 for m in amending if not m.get("amends_act_id"))
    print(f"wrote {OUT.relative_to(C.ROOT)}: {len(principal)} principal rows; "
          f"{len(amending)} amending Acts, {unlinked} without a principal target")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
